unit uWMSArticleFile;

interface

uses
  uFTPFiles, uGestionBDD;

type
  TWMSArticleFile = class(TCustomFTPSendFile)
  protected
    procedure LoadQueryParams(AQuery: TMyQuery); override;

    function getQuery: string; override;
    function getInitQuery: string; override;

  public
  end;

implementation

uses
  uCustomFTPManager, uCommon_Dm;

{ TWMSArticleFile }

function TWMSArticleFile.getInitQuery: string;
begin
  Result :=
    'SELECT ' +
    '  CBI_CB, ' +
    '  ART_REFMRK, ART_NOM, ' +
    '  '''' AS EMPTY, ' +
    '  MRK_NOM, ' +
    '  ARF_CHRONO, ' +
    '  COU_CODE || ''/'' || COU_NOM AS COULEUR, ' +
    '  ARF_ARCHIVER, ' +
    '  GRE_NOM, ' +
    '  TGF_NOM, ' +
    '  '''' AS EMPTY, ' +
    '  '''' AS EMPTY, ' +
    '  FAM_NOM || ''/'' || SSF_NOM AS FAMILLESOUSFAMILLE, ' +
    '  UNI_NOM || ''/'' || RAY_NOM AS UNIVERRAYON , ' +
    '  ARF_VIRTUEL, ' +
    '  ARW_POIDS, POID.PDS_LIBELLE, ARW_POIDSL, POIDL.PDS_LIBELLE, KART.K_ENABLED ' +
    'FROM ' +
    '  ARTARTICLE JOIN K KART ON KART.K_ID = ARTARTICLE.ART_ID AND KART.K_ENABLED = 1 ' +
    '  JOIN ARTREFERENCE ON ARF_ARTID = ART_ID AND ARF_ARCHIVER = 0 ' +
    '  JOIN ARTCODEBARRE JOIN K KCBI ON KCBI.K_ID = CBI_ID AND KCBI.K_ENABLED = 1 ' +
    '    ON CBI_ARFID = ARF_ID and CBI_TYPE = 1 ' +
    '  JOIN PLXCOULEUR ON PLXCOULEUR.COU_ID = ARTCODEBARRE.CBI_COUID ' +
    '  JOIN PLXTAILLESGF ON PLXTAILLESGF.TGF_ID = ARTCODEBARRE.CBI_TGFID ' +
    '  JOIN ARTMARQUE ON ARTMARQUE.MRK_ID = ARTARTICLE.ART_MRKID ' +
    '  JOIN ARTGENRE ON ARTGENRE.GRE_ID = ARTARTICLE.ART_GREID ' +
    '  JOIN ARTRELATIONAXE ' +
    '    JOIN K KARX ON KARX.K_ID = ARTRELATIONAXE.ARX_ID AND KARX.K_ENABLED = 1 ' +
    '    ON ARTRELATIONAXE.ARX_ARTID = ARTARTICLE.ART_ID ' +
    '  JOIN NKLSSFAMILLE ON NKLSSFAMILLE.SSF_ID = ARTRELATIONAXE.ARX_SSFID ' +
    '  JOIN NKLFAMILLE ON NKLFAMILLE.FAM_ID = NKLSSFAMILLE.SSF_FAMID ' +
    '  JOIN NKLRAYON ON NKLRAYON.RAY_ID = NKLFAMILLE.FAM_RAYID ' +
    '  JOIN NKLSECTEUR ON NKLSECTEUR.SEC_ID = NKLRAYON.RAY_SECID ' +
    '  JOIN NKLUNIVERS ON NKLUNIVERS.UNI_ID = NKLSECTEUR.SEC_UNIID AND NKLUNIVERS.UNI_ACTID = ARTARTICLE.ART_ACTID ' +
    '  LEFT JOIN ARTWEB ON ARTWEB.ARW_ARTID = ARTARTICLE.ART_ID ' +
    '  LEFT JOIN GENPOIDS POID ON POID.PDS_ID = ARTWEB.ARW_PDSID ' +
    '  LEFT JOIN GENPOIDS POIDL ON POIDL.PDS_ID = ARTWEB.ARW_PDSIDL ' +
    'ORDER BY CBI_CB ';
end;

function TWMSArticleFile.getQuery: string;
begin
  Result := 'select CBI_CB, ART_REFMRK, ART_NOM, '''' as EMPTY, MRK_NOM, ARF_CHRONO, COU_CODE || ''/'' || COU_NOM as COULEUR, ARF_ARCHIVER, GRE_NOM, TGF_NOM, ';
  Result := Result + ''''' as EMPTY, '''' as EMPTY, FAM_NOM || ''/'' || SSF_NOM as FAMILLESOUSFAMILLE, UNI_NOM || ''/'' || RAY_NOM as UNIVERRAYON, ';
  Result := Result + 'ARF_VIRTUEL, ARW_POIDS, POID.PDS_LIBELLE, ARW_POIDSL, POIDL.PDS_LIBELLE, KART.K_ENABLED ';
  Result := Result + 'from ARTARTICLE  join K KART on (KART.K_ID = ARTARTICLE.ART_ID) ';
  Result := Result + 'join ARTREFERENCE on (ARF_ARTID = ART_ID)  join K KARF on (KARF.K_ID = ARTREFERENCE.ARF_ID) ';
  Result := Result + 'join ARTCODEBARRE on (CBI_ARFID = ARF_ID and CBI_TYPE = 1)  join K KCBI on (KCBI.K_ID = CBI_ID) ';
  Result := Result + 'join PLXCOULEUR on (PLXCOULEUR.COU_ID = ARTCODEBARRE.CBI_COUID)  join K KCOU on (KCOU.K_ID = PLXCOULEUR.COU_ID) ';
  Result := Result + 'join PLXTAILLESGF on (PLXTAILLESGF.TGF_ID = ARTCODEBARRE.CBI_TGFID)  join K KTGF on (KTGF.K_ID = PLXTAILLESGF.TGF_ID) ';
  Result := Result + 'join ARTMARQUE on (ARTMARQUE.MRK_ID = ARTARTICLE.ART_MRKID)  join K KMRK on (KMRK.K_ID = ARTMARQUE.MRK_ID) ';
  Result := Result + 'join ARTGENRE on (ARTGENRE.GRE_ID = ARTARTICLE.ART_GREID) ';
  Result := Result + 'join ARTRELATIONAXE on (ARTRELATIONAXE.ARX_ARTID = ARTARTICLE.ART_ID)  join K KARX on (KARX.K_ID = ARTRELATIONAXE.ARX_ID and KARX.K_ENABLED = 1) ';
  Result := Result + 'join NKLSSFAMILLE on (NKLSSFAMILLE.SSF_ID = ARTRELATIONAXE.ARX_SSFID)  join K KSSF on (KSSF.K_ID = NKLSSFAMILLE.SSF_ID) ';
  Result := Result + 'join NKLFAMILLE on (NKLFAMILLE.FAM_ID = NKLSSFAMILLE.SSF_FAMID)  join K KFAM on (KFAM.K_ID = NKLFAMILLE.FAM_ID) ';
  Result := Result + 'join NKLRAYON on (NKLRAYON.RAY_ID = NKLFAMILLE.FAM_RAYID)  join K KRAY on (KRAY.K_ID = NKLRAYON.RAY_ID) ';
  Result := Result + 'join NKLUNIVERS on (NKLUNIVERS.UNI_ID = NKLRAYON.RAY_UNIID)  join K KUNI on (KUNI.K_ID = NKLUNIVERS.UNI_ID) ';
  Result := Result + 'left join ARTWEB on (ARTWEB.ARW_ARTID = ARTARTICLE.ART_ID) ';
  Result := Result + 'left join GENPOIDS POID on (POID.PDS_ID = ARTWEB.ARW_PDSID) ';
  Result := Result + 'left join GENPOIDS POIDL on (POIDL.PDS_ID = ARTWEB.ARW_PDSIDL) ';
  Result := Result + 'where ((KART.KRH_ID > :LAST_VERSION and KART.KRH_ID <= :CURRENT_VERSION) or (KART.K_VERSION > :LAST_VERSION_LAME and KART.K_VERSION <= :CURRENT_VERSION_LAME and not(KART.KRH_ID > :DEBUT_PLAGE_BASE and KART.KRH_ID <= :FIN_PLAGE_BASE))) ';
  Result := Result + '   or ((KARF.KRH_ID > :LAST_VERSION and KARF.KRH_ID <= :CURRENT_VERSION) or (KARF.K_VERSION > :LAST_VERSION_LAME and KARF.K_VERSION <= :CURRENT_VERSION_LAME and not(KARF.KRH_ID > :DEBUT_PLAGE_BASE and KARF.KRH_ID <= :FIN_PLAGE_BASE))) ';
  Result := Result + '   or ((KCBI.KRH_ID > :LAST_VERSION and KCBI.KRH_ID <= :CURRENT_VERSION) or (KCBI.K_VERSION > :LAST_VERSION_LAME and KCBI.K_VERSION <= :CURRENT_VERSION_LAME and not(KCBI.KRH_ID > :DEBUT_PLAGE_BASE and KCBI.KRH_ID <= :FIN_PLAGE_BASE))) ';
  Result := Result + '   or ((KCOU.KRH_ID > :LAST_VERSION and KCOU.KRH_ID <= :CURRENT_VERSION) or (KCOU.K_VERSION > :LAST_VERSION_LAME and KCOU.K_VERSION <= :CURRENT_VERSION_LAME and not(KCOU.KRH_ID > :DEBUT_PLAGE_BASE and KCOU.KRH_ID <= :FIN_PLAGE_BASE))) ';
  Result := Result + '   or ((KTGF.KRH_ID > :LAST_VERSION and KTGF.KRH_ID <= :CURRENT_VERSION) or (KTGF.K_VERSION > :LAST_VERSION_LAME and KTGF.K_VERSION <= :CURRENT_VERSION_LAME and not(KTGF.KRH_ID > :DEBUT_PLAGE_BASE and KTGF.KRH_ID <= :FIN_PLAGE_BASE))) ';
  Result := Result + '   or ((KMRK.KRH_ID > :LAST_VERSION and KMRK.KRH_ID <= :CURRENT_VERSION) or (KMRK.K_VERSION > :LAST_VERSION_LAME and KMRK.K_VERSION <= :CURRENT_VERSION_LAME and not(KMRK.KRH_ID > :DEBUT_PLAGE_BASE and KMRK.KRH_ID <= :FIN_PLAGE_BASE))) ';
  Result := Result + '   or ((KARX.KRH_ID > :LAST_VERSION and KARX.KRH_ID <= :CURRENT_VERSION) or (KARX.K_VERSION > :LAST_VERSION_LAME and KARX.K_VERSION <= :CURRENT_VERSION_LAME and not(KARX.KRH_ID > :DEBUT_PLAGE_BASE and KARX.KRH_ID <= :FIN_PLAGE_BASE))) ';
  Result := Result + '   or ((KSSF.KRH_ID > :LAST_VERSION and KSSF.KRH_ID <= :CURRENT_VERSION) or (KSSF.K_VERSION > :LAST_VERSION_LAME and KSSF.K_VERSION <= :CURRENT_VERSION_LAME and not(KSSF.KRH_ID > :DEBUT_PLAGE_BASE and KSSF.KRH_ID <= :FIN_PLAGE_BASE))) ';
  Result := Result + '   or ((KFAM.KRH_ID > :LAST_VERSION and KFAM.KRH_ID <= :CURRENT_VERSION) or (KFAM.K_VERSION > :LAST_VERSION_LAME and KFAM.K_VERSION <= :CURRENT_VERSION_LAME and not(KFAM.KRH_ID > :DEBUT_PLAGE_BASE and KFAM.KRH_ID <= :FIN_PLAGE_BASE))) ';
  Result := Result + '   or ((KRAY.KRH_ID > :LAST_VERSION and KRAY.KRH_ID <= :CURRENT_VERSION) or (KRAY.K_VERSION > :LAST_VERSION_LAME and KRAY.K_VERSION <= :CURRENT_VERSION_LAME and not(KRAY.KRH_ID > :DEBUT_PLAGE_BASE and KRAY.KRH_ID <= :FIN_PLAGE_BASE))) ';
  Result := Result + '   or ((KUNI.KRH_ID > :LAST_VERSION and KUNI.KRH_ID <= :CURRENT_VERSION) or (KUNI.K_VERSION > :LAST_VERSION_LAME and KUNI.K_VERSION <= :CURRENT_VERSION_LAME and not(KUNI.KRH_ID > :DEBUT_PLAGE_BASE and KUNI.KRH_ID <= :FIN_PLAGE_BASE))) ';
  Result := Result + 'union ';
  Result := Result + 'select CBI_CB, ART_REFMRK, ART_NOM, '''' as EMPTY, MRK_NOM, ARF_CHRONO, COU_CODE || ''/'' || COU_NOM as COULEUR, ARF_ARCHIVER, GRE_NOM, TGF_NOM, ';
  Result := Result + ''''' as EMPTY, '''' as EMPTY, FAM_NOM || ''/'' || SSF_NOM as FAMILLESOUSFAMILLE, UNI_NOM || ''/'' || RAY_NOM as UNIVERRAYON, ';
  Result := Result + 'ARF_VIRTUEL, ARW_POIDS, POID.PDS_LIBELLE, ARW_POIDSL, POIDL.PDS_LIBELLE, KART.K_ENABLED ';
  Result := Result + 'from ARTARTICLE  join K KART on (KART.K_ID = ARTARTICLE.ART_ID) ';
  Result := Result + 'join ARTREFERENCE on (ARF_ARTID = ART_ID)  join K KARF on (KARF.K_ID = ARTREFERENCE.ARF_ID) ';
  Result := Result + 'join ARTCODEBARRE on (CBI_ARFID = ARF_ID and CBI_TYPE = 1)  join K KCBI on (KCBI.K_ID = CBI_ID) ';
  Result := Result + 'join PLXCOULEUR on (PLXCOULEUR.COU_ID = ARTCODEBARRE.CBI_COUID)  join K KCOU on (KCOU.K_ID = PLXCOULEUR.COU_ID) ';
  Result := Result + 'join PLXTAILLESGF on (PLXTAILLESGF.TGF_ID = ARTCODEBARRE.CBI_TGFID)  join K KTGF on (KTGF.K_ID = PLXTAILLESGF.TGF_ID) ';
  Result := Result + 'join ARTMARQUE on (ARTMARQUE.MRK_ID = ARTARTICLE.ART_MRKID)  join K KMRK on (KMRK.K_ID = ARTMARQUE.MRK_ID) ';
  Result := Result + 'join ARTGENRE on (ARTGENRE.GRE_ID = ARTARTICLE.ART_GREID) ';
  Result := Result + 'join ARTRELATIONAXE on (ARTRELATIONAXE.ARX_ARTID = ARTARTICLE.ART_ID)  join K KARX on (KARX.K_ID = ARTRELATIONAXE.ARX_ID and KARX.K_ENABLED = 1) ';
  Result := Result + 'join NKLSSFAMILLE on (NKLSSFAMILLE.SSF_ID = ARTRELATIONAXE.ARX_SSFID)  join K KSSF on (KSSF.K_ID = NKLSSFAMILLE.SSF_ID) ';
  Result := Result + 'join NKLFAMILLE on (NKLFAMILLE.FAM_ID = NKLSSFAMILLE.SSF_FAMID)  join K KFAM on (KFAM.K_ID = NKLFAMILLE.FAM_ID) ';
  Result := Result + 'join NKLRAYON on (NKLRAYON.RAY_ID = NKLFAMILLE.FAM_RAYID)  join K KRAY on (KRAY.K_ID = NKLRAYON.RAY_ID) ';
  Result := Result + 'join NKLUNIVERS on (NKLUNIVERS.UNI_ID = NKLRAYON.RAY_UNIID)  join K KUNI on (KUNI.K_ID = NKLUNIVERS.UNI_ID) ';
  Result := Result + 'join ARTWEB on (ARTWEB.ARW_ARTID = ARTARTICLE.ART_ID)  join K KARW on (KARW.K_ID = ARTWEB.ARW_ID) ';
  Result := Result + 'join GENPOIDS POID on (POID.PDS_ID = ARTWEB.ARW_PDSID) ';
  Result := Result + 'join GENPOIDS POIDL on (POIDL.PDS_ID = ARTWEB.ARW_PDSIDL) ';
  Result := Result + 'where (ARW_WEB = 1 ';
  Result := Result + 'and ((KARW.KRH_ID > :LAST_VERSION and KARW.KRH_ID <= :CURRENT_VERSION) or (KARW.K_VERSION > :LAST_VERSION_LAME and KARW.K_VERSION <= :CURRENT_VERSION_LAME and not(KARW.KRH_ID > :DEBUT_PLAGE_BASE and KARW.KRH_ID <= :FIN_PLAGE_BASE)))) ';
  Result := Result + 'order by 1';


{  Result :=
    'SELECT ' +
    '  CBI_CB, ' +
    '  ART_REFMRK, ART_NOM, ' +
    '  '''' AS EMPTY, ' +
    '  MRK_NOM, ' +
    '  ARF_CHRONO, ' +
    '  COU_CODE || ''/'' || COU_NOM AS COULEUR, ' +
    '  ARF_ARCHIVER, ' +
    '  GRE_NOM, ' +
    '  TGF_NOM, ' +
    '  '''' AS EMPTY, ' +
    '  '''' AS EMPTY, ' +
    '  FAM_NOM || ''/'' || SSF_NOM AS FAMILLESOUSFAMILLE, ' +
    '  UNI_NOM || ''/'' || RAY_NOM AS UNIVERRAYON , ' +
    '  ARF_VIRTUEL, ' +
    '  ARW_POIDS, POID.PDS_LIBELLE, ARW_POIDSL, POIDL.PDS_LIBELLE, KART.K_ENABLED ' +
    'FROM ' +
    '  ARTARTICLE JOIN K KART ON KART.K_ID = ARTARTICLE.ART_ID ' +
    '  JOIN ARTREFERENCE ' +
    '    JOIN K KARF ON KARF.K_ID = ARTREFERENCE.ARF_ID ' +
    '    ON ARF_ARTID = ART_ID ' +
    '  JOIN ARTCODEBARRE ' +
    '    JOIN K KCBI ON KCBI.K_ID = CBI_ID ' +
    '    ON CBI_ARFID = ARF_ID and CBI_TYPE = 1 ' +
    '  JOIN PLXCOULEUR ' +
    '    JOIN K KCOU ON KCOU.K_ID = PLXCOULEUR.COU_ID ' +
    '    ON PLXCOULEUR.COU_ID = ARTCODEBARRE.CBI_COUID ' +
    '  JOIN PLXTAILLESGF ' +
    '    JOIN K KTGF ON KTGF.K_ID = PLXTAILLESGF.TGF_ID ' +
    '    ON PLXTAILLESGF.TGF_ID = ARTCODEBARRE.CBI_TGFID ' +
    '  JOIN ARTMARQUE ' +
    '    JOIN K KMRK ON KMRK.K_ID = ARTMARQUE.MRK_ID ' +
    '    ON ARTMARQUE.MRK_ID = ARTARTICLE.ART_MRKID ' +
    '  JOIN ARTGENRE ON ARTGENRE.GRE_ID = ARTARTICLE.ART_GREID ' +
    '  JOIN ARTRELATIONAXE ' +
    '    JOIN K KARX ON KARX.K_ID = ARTRELATIONAXE.ARX_ID AND KARX.K_ENABLED = 1 ' +
    '    ON ARTRELATIONAXE.ARX_ARTID = ARTARTICLE.ART_ID ' +
    '  JOIN NKLSSFAMILLE ' +
    '    JOIN K KSSF ON KSSF.K_ID = NKLSSFAMILLE.SSF_ID ' +
    '    ON NKLSSFAMILLE.SSF_ID = ARTRELATIONAXE.ARX_SSFID ' +
    '  JOIN NKLFAMILLE ' +
    '    JOIN K KFAM ON KFAM.K_ID = NKLFAMILLE.FAM_ID ' +
    '    ON NKLFAMILLE.FAM_ID = NKLSSFAMILLE.SSF_FAMID ' +
    '  JOIN NKLRAYON ' +
    '    JOIN K KRAY ON KRAY.K_ID = NKLRAYON.RAY_ID ' +
    '    ON NKLRAYON.RAY_ID = NKLFAMILLE.FAM_RAYID ' +
    '  JOIN NKLUNIVERS ' +
    '    JOIN K KUNI ON KUNI.K_ID = NKLUNIVERS.UNI_ID ' +
    '    ON NKLUNIVERS.UNI_ID = NKLRAYON.RAY_UNIID ' +
    '  LEFT JOIN ARTWEB JOIN K KARW ON KARW.K_ID = ARTWEB.ARW_ID ' +
    '    ON ARTWEB.ARW_ARTID = ARTARTICLE.ART_ID ' +
    '  LEFT JOIN GENPOIDS POID ON POID.PDS_ID = ARTWEB.ARW_PDSID ' +
    '  LEFT JOIN GENPOIDS POIDL ON POIDL.PDS_ID = ARTWEB.ARW_PDSIDL ' +
    'WHERE ' +
    '  ((KART.KRH_ID > :LAST_VERSION AND KART.KRH_ID <= :CURRENT_VERSION) ' +
    '    OR (KART.K_VERSION > :LAST_VERSION_LAME AND KART.K_VERSION <= :CURRENT_VERSION_LAME ' +
    '    AND NOT(KART.KRH_ID > :DEBUT_PLAGE_BASE AND KART.KRH_ID <= :FIN_PLAGE_BASE))) ' +
    '  OR ((KARF.KRH_ID > :LAST_VERSION AND KARF.KRH_ID <= :CURRENT_VERSION) ' +
    '    OR (KARF.K_VERSION > :LAST_VERSION_LAME AND KARF.K_VERSION <= :CURRENT_VERSION_LAME ' +
    '    AND NOT(KARF.KRH_ID > :DEBUT_PLAGE_BASE AND KARF.KRH_ID <= :FIN_PLAGE_BASE))) ' +
    '  OR ((KCBI.KRH_ID > :LAST_VERSION AND KCBI.KRH_ID <= :CURRENT_VERSION) ' +
    '    OR (KCBI.K_VERSION > :LAST_VERSION_LAME AND KCBI.K_VERSION <= :CURRENT_VERSION_LAME ' +
    '    AND NOT(KCBI.KRH_ID > :DEBUT_PLAGE_BASE AND KCBI.KRH_ID <= :FIN_PLAGE_BASE))) ' +
    '  OR ((KCOU.KRH_ID > :LAST_VERSION AND KCOU.KRH_ID <= :CURRENT_VERSION) ' +
    '    OR (KCOU.K_VERSION > :LAST_VERSION_LAME AND KCOU.K_VERSION <= :CURRENT_VERSION_LAME ' +
    '    AND NOT(KCOU.KRH_ID > :DEBUT_PLAGE_BASE AND KCOU.KRH_ID <= :FIN_PLAGE_BASE))) ' +
    '  OR ((KTGF.KRH_ID > :LAST_VERSION AND KTGF.KRH_ID <= :CURRENT_VERSION) ' +
    '    OR (KTGF.K_VERSION > :LAST_VERSION_LAME AND KTGF.K_VERSION <= :CURRENT_VERSION_LAME ' +
    '    AND NOT(KTGF.KRH_ID > :DEBUT_PLAGE_BASE AND KTGF.KRH_ID <= :FIN_PLAGE_BASE))) ' +
    '  OR ((KMRK.KRH_ID > :LAST_VERSION AND KMRK.KRH_ID <= :CURRENT_VERSION) ' +
    '    OR (KMRK.K_VERSION > :LAST_VERSION_LAME AND KMRK.K_VERSION <= :CURRENT_VERSION_LAME ' +
    '    AND NOT(KMRK.KRH_ID > :DEBUT_PLAGE_BASE AND KMRK.KRH_ID <= :FIN_PLAGE_BASE))) ' +
    '  OR ((KARX.KRH_ID > :LAST_VERSION AND KARX.KRH_ID <= :CURRENT_VERSION) ' +
    '    OR (KARX.K_VERSION > :LAST_VERSION_LAME AND KARX.K_VERSION <= :CURRENT_VERSION_LAME ' +
    '    AND NOT(KARX.KRH_ID > :DEBUT_PLAGE_BASE AND KARX.KRH_ID <= :FIN_PLAGE_BASE))) ' +
    '  OR ((KSSF.KRH_ID > :LAST_VERSION AND KSSF.KRH_ID <= :CURRENT_VERSION) ' +
    '    OR (KSSF.K_VERSION > :LAST_VERSION_LAME AND KSSF.K_VERSION <= :CURRENT_VERSION_LAME ' +
    '    AND NOT(KSSF.KRH_ID > :DEBUT_PLAGE_BASE AND KSSF.KRH_ID <= :FIN_PLAGE_BASE))) ' +
    '  OR ((KFAM.KRH_ID > :LAST_VERSION AND KFAM.KRH_ID <= :CURRENT_VERSION) ' +
    '    OR (KFAM.K_VERSION > :LAST_VERSION_LAME AND KFAM.K_VERSION <= :CURRENT_VERSION_LAME ' +
    '    AND NOT(KFAM.KRH_ID > :DEBUT_PLAGE_BASE AND KFAM.KRH_ID <= :FIN_PLAGE_BASE))) ' +
    '  OR ((KRAY.KRH_ID > :LAST_VERSION AND KRAY.KRH_ID <= :CURRENT_VERSION) ' +
    '    OR (KRAY.K_VERSION > :LAST_VERSION_LAME AND KRAY.K_VERSION <= :CURRENT_VERSION_LAME ' +
    '    AND NOT(KRAY.KRH_ID > :DEBUT_PLAGE_BASE AND KRAY.KRH_ID <= :FIN_PLAGE_BASE))) ' +
    '  OR ((KUNI.KRH_ID > :LAST_VERSION AND KUNI.KRH_ID <= :CURRENT_VERSION) ' +
    '    OR (KUNI.K_VERSION > :LAST_VERSION_LAME AND KUNI.K_VERSION <= :CURRENT_VERSION_LAME ' +
    '    AND NOT(KUNI.KRH_ID > :DEBUT_PLAGE_BASE AND KUNI.KRH_ID <= :FIN_PLAGE_BASE))) ' +
    'UNION ' +
    'SELECT ' +
    '  CBI_CB, ' +
    '  ART_REFMRK, ART_NOM, ' +
    '  '''' AS EMPTY, ' +
    '  MRK_NOM, ' +
    '  ARF_CHRONO, ' +
    '  COU_CODE || ''/'' || COU_NOM AS COULEUR, ' +
    '  ARF_ARCHIVER, ' +
    '  GRE_NOM, ' +
    '  TGF_NOM, ' +
    '  '''' AS EMPTY, ' +
    '  '''' AS EMPTY, ' +
    '  FAM_NOM || ''/'' || SSF_NOM AS FAMILLESOUSFAMILLE, ' +
    '  UNI_NOM || ''/'' || RAY_NOM AS UNIVERRAYON , ' +
    '  ARF_VIRTUEL, ' +
    '  ARW_POIDS, POID.PDS_LIBELLE, ARW_POIDSL, POIDL.PDS_LIBELLE, KART.K_ENABLED ' +
    'FROM ' +
    '  ARTARTICLE JOIN K KART ON KART.K_ID = ARTARTICLE.ART_ID ' +
    '  JOIN ARTREFERENCE ' +
    '    JOIN K KARF ON KARF.K_ID = ARTREFERENCE.ARF_ID ' +
    '    ON ARF_ARTID = ART_ID ' +
    '  JOIN ARTCODEBARRE ' +
    '    JOIN K KCBI ON KCBI.K_ID = CBI_ID ' +
    '    ON CBI_ARFID = ARF_ID and CBI_TYPE = 1 ' +
    '  JOIN PLXCOULEUR ' +
    '    JOIN K KCOU ON KCOU.K_ID = PLXCOULEUR.COU_ID ' +
    '    ON PLXCOULEUR.COU_ID = ARTCODEBARRE.CBI_COUID ' +
    '  JOIN PLXTAILLESGF ' +
    '    JOIN K KTGF ON KTGF.K_ID = PLXTAILLESGF.TGF_ID ' +
    '    ON PLXTAILLESGF.TGF_ID = ARTCODEBARRE.CBI_TGFID ' +
    '  JOIN ARTMARQUE ' +
    '    JOIN K KMRK ON KMRK.K_ID = ARTMARQUE.MRK_ID ' +
    '    ON ARTMARQUE.MRK_ID = ARTARTICLE.ART_MRKID ' +
    '  JOIN ARTGENRE ON ARTGENRE.GRE_ID = ARTARTICLE.ART_GREID ' +
    '  JOIN ARTRELATIONAXE ' +
    '    JOIN K KARX ON KARX.K_ID = ARTRELATIONAXE.ARX_ID AND KARX.K_ENABLED = 1 ' +
    '    ON ARTRELATIONAXE.ARX_ARTID = ARTARTICLE.ART_ID ' +
    '  JOIN NKLSSFAMILLE ' +
    '    JOIN K KSSF ON KSSF.K_ID = NKLSSFAMILLE.SSF_ID ' +
    '    ON NKLSSFAMILLE.SSF_ID = ARTRELATIONAXE.ARX_SSFID ' +
    '  JOIN NKLFAMILLE ' +
    '    JOIN K KFAM ON KFAM.K_ID = NKLFAMILLE.FAM_ID ' +
    '    ON NKLFAMILLE.FAM_ID = NKLSSFAMILLE.SSF_FAMID ' +
    '  JOIN NKLRAYON ' +
    '    JOIN K KRAY ON KRAY.K_ID = NKLRAYON.RAY_ID ' +
    '    ON NKLRAYON.RAY_ID = NKLFAMILLE.FAM_RAYID ' +
    '  JOIN NKLUNIVERS ' +
    '    JOIN K KUNI ON KUNI.K_ID = NKLUNIVERS.UNI_ID ' +
    '    ON NKLUNIVERS.UNI_ID = NKLRAYON.RAY_UNIID ' +
    '  JOIN ARTWEB JOIN K KARW ON KARW.K_ID = ARTWEB.ARW_ID ' +
    '    ON ARTWEB.ARW_ARTID = ARTARTICLE.ART_ID ' +
    '  JOIN GENPOIDS POID ON POID.PDS_ID = ARTWEB.ARW_PDSID ' +
    '  JOIN GENPOIDS POIDL ON POIDL.PDS_ID = ARTWEB.ARW_PDSIDL ' +
    'WHERE ' +
    '  (ARW_WEB = 1 AND ((KARW.KRH_ID > :LAST_VERSION AND KARW.KRH_ID <= :CURRENT_VERSION) ' +
    '    OR (KARW.K_VERSION > :LAST_VERSION_LAME AND KARW.K_VERSION <= :CURRENT_VERSION_LAME ' +
    '    AND NOT(KARW.KRH_ID > :DEBUT_PLAGE_BASE AND KARW.KRH_ID <= :FIN_PLAGE_BASE)))) ' +
    'ORDER BY 1';  }
end;

procedure TWMSArticleFile.LoadQueryParams(AQuery: TMyQuery);
begin
  inherited LoadQueryParams(AQuery);
end;

initialization
  TCustomFTPManager.RegisterKnownFile('WMS_ART', ftSend, '', '', TWMSArticleFile);
end.

